apiVersion: rds.aws.crossplane.io/v1alpha1
kind: GlobalCluster
metadata:
  name: example-globalcluster
spec:
  forProvider:
    sourceDBClusterIdentifierRef:
      name: example-dbcluster
    region: us-east-1
  providerConfigRef:
    name: example