resources:
  Server:
    exceptions:
      errors:
        404:
          code: ResourceNotFoundException
  User:
    exceptions:
      errors:
        404:
          code: ResourceNotFoundException    
