apiVersion: efs.aws.crossplane.io/v1alpha1
kind: MountTarget
metadata:
  name: example
spec:
  forProvider:
    region: us-east-1
    fileSystemID: fs-0668c05d
    subnetID: subnet-f2ccb898
    securityGroupsRefs:
      - name: sample-cluster-sg
  providerConfigRef:
    name: example
