apiVersion: glue.aws.crossplane.io/v1alpha1
kind: Classifier
metadata:
  name: glue-classifier
spec:
  forProvider:
    region: us-east-1
    csvClassifier:
      delimiter: ","
      quoteSymbol: "\""
      name: "glue-classifier"
      containsHeader: "PRESENT"
      disableValueTrimming: true 
      allowSingleColumn: false
  providerConfigRef:
    name: example
