apiVersion: glue.aws.crossplane.io/v1alpha1
kind: Crawler
metadata:
  name: glue-crawler
spec:
  forProvider:
    region: us-east-1
    classifiers:
      - "glue-classifier"
    configuration: ""
    crawlerSecurityConfiguration: "glue-securityconfiguration"
    databaseName: "glue-database"
    lineageConfiguration: 
      crawlerLineageSettings: "ENABLE"
    name: "glue-crawler"
    recrawlPolicy: 
      recrawlBehavior: "CRAWL_EVERYTHING"
    role: "arn:aws:iam::255932642927:role/aws-glue"
    schedule: "Cron(5,15,25,35,45,55 * * * ? *)"
    schemaChangePolicy:
      deleteBehavior: "DELETE_FROM_DATABASE"
      updateBehavior: "UPDATE_IN_DATABASE"
    tablePrefix: ""
    tags:
      glue: "crawler"
    targets: 
      jdbcTargets: [
        connectionName: "glue-connection",
      ]
  providerConfigRef:
    name: example
