apiVersion: glue.aws.crossplane.io/v1alpha1
kind: Database
metadata:
  name: glue-database
spec:
  forProvider:
    region: us-east-1
    databaseInput: 
      name: "glue-database"
  providerConfigRef:
    name: example
