ignore:
  resource_names:
    - CapacityReservation
    - CarrierGateway
    - ClientVpnEndpoint
    - ClientVpnRoute
    - CustomerGateway
    - DefaultSubnet
    - DefaultVpc
    - EgressOnlyInternetGateway
    - Fleet
    - FpgaImage
    - Image
    - InstanceExportTask
    - InternetGateway
    - KeyPair
    - LaunchTemplateVersion
    - LaunchTemplate
    - LocalGatewayRouteTableVpcAssociation
    - LocalGatewayRoute
    - ManagedPrefixList
    - NatGateway
    - NetworkAclEntry
    - NetworkAcl
    - NetworkInsightsPath
    - NetworkInterfacePermission
    - NetworkInterface
    - PlacementGroup
    - ReservedInstancesListing
    - RouteTable
    - SecurityGroup
    - Snapshot
    - SpotDatafeedSubscription
    - Subnet 
    - TrafficMirrorFilterRule
    - TrafficMirrorFilter
    - TrafficMirrorSession
    - TrafficMirrorTarget
    - TransitGatewayConnectPeer
    - TransitGatewayConnect
    - TransitGatewayMulticastDomain
    - TransitGatewayPeeringAttachment
    - TransitGatewayPrefixListReference
    - TransitGatewayRouteTable
    - TransitGatewayRoute
    - TransitGatewayVpcAttachment
    - TransitGateway
    - VpcEndpointConnectionNotification
    - VpcEndpointServiceConfiguration
    - VpcEndpoint
    - VpcPeeringConnection
    - VpcCidrBlock
    - Vpc 
    - VpnConnectionRoute
    - VpnConnection
    - VpnGateway
    - Volume