ignore:
  resource_names:
    - AccessPoint
  field_paths:
    - CreateFileSystemInput.CreationToken
    - CreateFileSystemInput.ProvisionedThroughputInMibps
    - UpdateFileSystemInput.ProvisionedThroughputInMibps
    - FileSystemDescription.ProvisionedThroughputInMibps
    - CreateMountTargetInput.SecurityGroups
resources:
  MountTarget:
    exceptions:
      errors:
        404:
          code: MountTargetNotFound
