ignore:
  field_paths:
    - CreateClusterInput.BrokerNodeGroupInfo
    - CreateClusterInput.ClusterName
    - CreateClusterInput.ConfigurationInfo
    - CreateConfigurationInput.Name
    - CreateConfigurationInput.ServerProperties
resources:
  Configuration:
    exceptions:
      errors:
        404:
          # failed to describe Configuration: BadRequestException: Configuration ARN does not exist
          code: BadRequestException
  Cluster:
    exceptions:
      errors:
        404:
          code: NotFoundException
